# Compile the Java source files into class files
build:
	javac com/orderprocessor/*.java
	javac a.java

# Clean up any previous build files
clean:
	rm -f com/orderprocessor/*.class
	rm -f a.class

# Build and run the program
run: build
	java a
